
spring:
  application:
    name: igtools
    businessName: Common FB features client
  datasource:
    url: "jdbc:postgresql://ec2-54-145-188-92.compute-1.amazonaws.com:5432/d6nuqi6avckvaq"
    username: dlmvmmuribpdse
    password: ${DATABASE_PSS}
    driver-class-name: org.postgresql.Driver
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL94Dialect
  jpa:
    show-sql: false
    properties:
      javax:
        persistence:
          schema-generation:
            scripts:
              action: none #none, create, drop, drop-and-create
              create-target: create.sql
              create-source: metadata
              drop-target: drop.sql
              drop-source: metadata
      hibernate:
        generate_statistics: false
        jdbc:
          batch_size: 5000
          fetch_size: 5000
        order_inserts: true
        order_updates: true

api:
  graph:
    name: Graph-Api-Client
    url: https://graph.facebook.com
    api-version: v11.0
    retry:
      enable: true
      maxAttempts: 5
      interval: 1
  fb-commons:
    name: Fb-Commons-Api
    url: http://fb-graph-api-commons.herokuapp.com
    api-version: v1
    pss: ${FB_COMMONS_PSS}
    retry:
      enable: true
      maxAttempts: 5
      interval: 1

post:
  retries: 3